/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoinItem: typeof import('./src/components/CoinItem.vue')['default']
    CoinPreview: typeof import('./src/components/CoinPreview.vue')['default']
    CoinToWithdraw: typeof import('./src/components/CoinToWithdraw.vue')['default']
    DepositItem: typeof import('./src/components/DepositItem.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    NewsSelector: typeof import('./src/components/NewsSelector.vue')['default']
    NotificationItem: typeof import('./src/components/NotificationItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    TimeSelector: typeof import('./src/components/TimeSelector.vue')['default']
    ToggleButton: typeof import('./src/components/buttons/ToggleButton.vue')['default']
    TransactionItem: typeof import('./src/components/TransactionItem.vue')['default']
    WalletSelector: typeof import('./src/components/WalletSelector.vue')['default']
  }
}
